// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7L5RPHQ9pf8PxbhGZddBETBpFH1ISYw',
    appId: '1:402777997671:android:0862129f77feac5cef2fc2',
    messagingSenderId: '402777997671',
    projectId: 'shopsmart2023-f2cb9',
    storageBucket: 'shopsmart2023-f2cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCryd7bcFz5A8uP4ZlN6PSei_2Z2mr1lNw',
    appId: '1:402777997671:ios:1203cc8cee34d322ef2fc2',
    messagingSenderId: '402777997671',
    projectId: 'shopsmart2023-f2cb9',
    storageBucket: 'shopsmart2023-f2cb9.appspot.com',
    iosBundleId: 'com.example.shopsmartUsersAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCryd7bcFz5A8uP4ZlN6PSei_2Z2mr1lNw',
    appId: '1:402777997671:ios:dab606e0b697c912ef2fc2',
    messagingSenderId: '402777997671',
    projectId: 'shopsmart2023-f2cb9',
    storageBucket: 'shopsmart2023-f2cb9.appspot.com',
    iosBundleId: 'com.example.shopsmartUsersAr.RunnerTests',
  );
}
